# This Dockerfile creates a container with the necessary prerequisites
# to compile and run ProtoMS. This can be used as a base for a
# production environment or with Bitbucket Pipelines for automated testing.

# A container can be built from this file by running the below command in $PROTOMSHOME:
# docker build -t protoms-test-environment -f Dockerfile_test .

# An interactive image can then be started with
# docker run -it protoms-test-environment /bin/bash
From python:2.7.13

WORKDIR /

# set environment variables to replace function of amber.sh
ENV AMBERHOME /amber17
ENV PYTHONPATH /amber17/lib/python2.7/site-packages/
ENV PROTOMSHOME /protoms-dev

# due to dependency issues numpy and six must be install before pymbar
RUN apt-get update
RUN apt-get install -y cmake gfortran openmpi-bin libopenmpi-dev
# due to dependency issues numpy and six must be install before pymbar
RUN pip install --trusted-host pypi.python.org numpy six scipy matplotlib nose
RUN pip install --trusted-host pypi.python.org pymbar
RUN wget http://ambermd.org/downloads/install_ambertools.sh
RUN bash install_ambertools.sh -v 2 --non-conda -p /
