      write(printstring,*)
     . "Compiled on uos-206787 by aicm1f12 at 2014-07-18 16:44:45.089049",
     . "."
      call printBoxText(HEADER,printstring)
      write(printstring,*)
     . "Subversion version 49. If you have access to the subversion resp",
     . "ository you can extract the source code for this binary by typin",
     . "g"
      call printBoxText(HEADER,printstring)
      write(printstring,*)
     . "'svn co -r http://protoms.googlecode.com/svn/trunk 49'."
      call printBoxText(HEADER,printstring)
