c#############################################
c Include file listing all global 
c variables used in protoMC
c
c     (C) Christopher Woods, October 2004
c
c#############################################

      include 'dimensions.inc'
      include 'constants.inc'
      include 'enums.inc'
    
      include 'printer.inc'
      include 'splitter.inc'
      include 'keyset.inc'
      
      include 'movelist.inc'
      include 'metropolis.inc'
      
      include 'proteins.inc'
      include 'solutes.inc'
      include 'solvents.inc'

      include 'energies.inc'
      include 'averages.inc'

      include 'extraenergies.inc'
  
      include 'pressure.inc'

      include 'stacks.inc'

      include 'templates.inc'

      include 'parameters.inc'
      
      include 'flags.inc'
      include 'moves.inc'
      include 'simparams.inc'
      include 'parallel.inc'
     

           
     

