
c#########################################
c
c     This file contains the name of the
c     program, version and name of the 
c     executable
c
c     (C) Christopher Woods
c
c#########################################

c     The name of the program
      character*7 progname
      parameter(progname="ProtoMS")
      
c     The version of the program      
      character*11 progversion
      parameter(progversion="2.4RC1")
      
c     The name of the executable      
      character*8 exename
      parameter(exename="protoms2")
